# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XTCKrgAMh1C_2noMMJ1k1cbRteG0SvlH
"""

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("summarization", model="Falconsai/text_summarization")

import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModelForSeq2SeqLM
tokenizer = AutoTokenizer.from_pretrained("falconsai/text_summarization")
model = TFAutoModelForSeq2SeqLM.from_pretrained("falconsai/text_summarization")

import streamlit as st

# Streamlit UI
st.title("Text Summarization")

# Text input box
text_input = st.text_area("Enter Text:", "")

# Submission button
if st.button("Summarize"):
    # Tokenize input text
    inputs = tokenizer(text_input, return_tensors="tf", max_length=1024, truncation=True)

    # Generate summary
    summary_ids = model.generate(inputs["input_ids"])

    # Decode the summary
    summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

    # Display the summary
    st.subheader("Generated Summary")
    st.write(summary)